export const cities: any = [
    {"id": "11", "uf": "RO", "state": "Rondônia", "data": require("../assets/topojson/11.json")},
    {"id": "12", "uf": "AC", "state": "Acre", "data": require("../assets/topojson/12.json")},
    {"id": "13", "uf": "AM", "state": "Amazonas", "data": require("../assets/topojson/13.json")},
    {"id": "14", "uf": "RR", "state": "Roraima", "data": require("../assets/topojson/14.json")},
    {"id": "15", "uf": "PA", "state": "Pará", "data": require("../assets/topojson/15.json")},
    {"id": "16", "uf": "AP", "state": "Amapá", "data": require("../assets/topojson/16.json")},
    {"id": "17", "uf": "TO", "state": "Tocantins", "data": require("../assets/topojson/17.json")},
    {"id": "21", "uf": "MA", "state": "Maranhão", "data": require("../assets/topojson/21.json")},
    {"id": "22", "uf": "PI", "state": "Piauí", "data": require("../assets/topojson/22.json")},
    {"id": "23", "uf": "CE", "state": "Ceará", "data": require("../assets/topojson/23.json")},
    {"id": "24", "uf": "RN", "state": "Rio Grande do Norte", "data": require("../assets/topojson/24.json")},
    {"id": "25", "uf": "PB", "state": "Paraíba", "data": require("../assets/topojson/25.json")},
    {"id": "26", "uf": "PE", "state": "Pernambuco", "data": require("../assets/topojson/26.json")},
    {"id": "27", "uf": "AL", "state": "Alagoas", "data": require("../assets/topojson/27.json")},
    {"id": "28", "uf": "SE", "state": "Sergipe", "data": require("../assets/topojson/28.json")},
    {"id": "29", "uf": "BA", "state": "Bahia", "data": require("../assets/topojson/29.json")},
    {"id": "31", "uf": "MG", "state": "Minas Gerais", "data": require("../assets/topojson/31.json")},
    {"id": "32", "uf": "ES", "state": "Espírito Santo", "data": require("../assets/topojson/32.json")},
    {"id": "33", "uf": "RJ", "state": "Rio de Janeiro", "data": require("../assets/topojson/33.json")},
    {"id": "35", "uf": "SP", "state": "São Paulo", "data": require("../assets/topojson/35.json")},
    {"id": "41", "uf": "PR", "state": "Paraná", "data": require("../assets/topojson/41.json")},
    {"id": "42", "uf": "SC", "state": "Santa Catarina", "data": require("../assets/topojson/42.json")},
    {"id": "43", "uf": "RS", "state": "Rio Grande do Sul", "data": require("../assets/topojson/43.json")},
    {"id": "50", "uf": "MS", "state": "Mato Grosso do Sul", "data": require("../assets/topojson/50.json")},
    {"id": "51", "uf": "MT", "state": "Mato Grosso", "data": require("../assets/topojson/51.json")},
    {"id": "52", "uf": "GO", "state": "Goiás", "data": require("../assets/topojson/52.json")},
    {"id": "53", "uf": "DF", "state": "Distrito Federal", "data": require("../assets/topojson/53.json")}
]
