export const states: any = [
  { id: "RO", value: 1, region: 2, nameRegion: "Norte" }, // 11.json
  { id: "AC", value: 2, region: 2, nameRegion: "Norte" },
  { id: "AM", value: 3, region: 2, nameRegion: "Norte" },
  { id: "RR", value: 4, region: 2, nameRegion: "Norte" },
  { id: "PA", value: 5, region: 2, nameRegion: "Norte" },
  { id: "AP", value: 6, region: 2, nameRegion: "Norte" },
  { id: "TO", value: 7, region: 2, nameRegion: "Norte" },
  { id: "MA", value: 8, region: 10, nameRegion: "Nordeste" },
  { id: "PI", value: 9, region: 10, nameRegion: "Nordeste" },
  { id: "CE", value: 10, region: 10, nameRegion: "Nordeste" },
  { id: "RN", value: 11, region: 10, nameRegion: "Nordeste" },
  { id: "PB", value: 12, region: 10, nameRegion: "Nordeste" },
  { id: "PE", value: 13, region: 10, nameRegion: "Nordeste" },
  { id: "AL", value: 14, region: 10, nameRegion: "Nordeste" },
  { id: "SE", value: 15, region: 10, nameRegion: "Nordeste" },
  { id: "BA", value: 16, region: 10, nameRegion: "Nordeste" },
  { id: "MG", value: 17, region: 15, nameRegion: "Sudeste" },
  { id: "ES", value: 18, region: 15, nameRegion: "Sudeste" },
  { id: "RJ", value: 19, region: 15, nameRegion: "Sudeste" },
  { id: "SP", value: 20, region: 15, nameRegion: "Sudeste" },
  { id: "PR", value: 21, region: 20, nameRegion: "Sul" },
  { id: "SC", value: 22, region: 20, nameRegion: "Sul" },
  { id: "RS", value: 23, region: 20, nameRegion: "Sul" },
  { id: "MS", value: 24, region: 25, nameRegion: "Centro-Oeste" },
  { id: "MT", value: 25, region: 25, nameRegion: "Centro-Oeste" },
  { id: "GO", value: 26, region: 25, nameRegion: "Centro-Oeste" },
  { id: "DF", value: 27, region: 25, nameRegion: "Centro-Oeste" },
];
